### ISSUE TITLE
Dashboard not uder auth

### ISSUE THREAD

**Issue by ketanmujumdar** [NizarAbiZaher/nizzy-starter#7]
Firstly really awesome that you are doing this and making it opensource, loved your work. 

However when I try to click on dashboard it is not under auth? Is there documentation where I can find where I can move it?

**Comment by dpaulos6** [comment]
what do you mean? can you paste a screenshot of the issue?

**Comment by rameskum** [comment]
The question was about whether the dashboard is a protected route. If I am not mistaken, we can protect routes in middleware.ts

Including a boilerplate code in the middleware.ts file in the starter project might be a good feature.

**Comment by dpaulos6** [comment]
> The question was about whether the dashboard is a protected route. If I am not mistaken, we can protect routes in middleware.ts
> 
> 
> 
> Including a boilerplate code in the middleware.ts file in the starter project might be a good feature.

Oh got it! Yes it is possible to do so, you can either change `middleware.ts`, or on the dashboard file, import session and redirect if it's `null`.

I'm considering making a docs page for this project, to cover all aspects and have examples on how to further customize it and all of that. Would that be a good idea?

**Comment by rameskum** [comment]
Yes, documentation should be suitable for users to understand and customize as per their needs.

**Comment by dpaulos6** [comment]
Thanks for your feedback! Documentation is now under construction.
